services:
  ollama:
    image: ollama/ollama:latest
    container_name: openhermes-server
    ports:
      - 11434:11434
    volumes:
      - ollama-data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    restart: unless-stopped

volumes:
  ollama-data:
