services:
  diagnostic-agent:
    build: .
    container_name: enhanced-diagnostic-agent
    ports:
      - "8080:8080"
    volumes:
      # Persist agent memory across container restarts
      - agent_memory:/app/agent_memory
      # Mount logs for external monitoring if needed
      - ./logs:/app/logs
      # Mount models directory for TinyLlama and other local models
      - ./models:/app/models
      # Cache for sentence transformer models to speed up restarts
      - model_cache:/home/agent/.cache
      # Mount host network and system info for diagnostics
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc:/host/etc:ro
      # Add Docker socket for container monitoring
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # Mount host network and system info for diagnostics
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc:/host/etc:ro
      # Add Docker socket for container monitoring
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - PYTHONUNBUFFERED=1
      - HOST=0.0.0.0
      - PORT=5000
      - DEBUG=false
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONPATH=/app
      # Optionally specify TinyLlama model path if available
      - TINYLLAMA_MODEL_PATH=/app/models/tinyllama.gguf
    command: ["python3", "smart_agent_frontend.py"]
    command: ["python3", "smart_agent_frontend.py"]
    restart: unless-stopped
    # Network mode to access host network stack for diagnostics
    network_mode: "host"
    privileged: false
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_ADMIN
    # Network mode to access host network stack for diagnostics
    network_mode: "host"
    privileged: false
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_ADMIN
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 60s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    # Resource limits for Pi deployment
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    security_opt:
      - no-new-privileges:true
    # Read-only root filesystem for enhanced security (with tmpfs for temp files)
    # Temporarily disabled for development - re-enable for production
    # read_only: true
    tmpfs:
      - /tmp
      - /var/tmp
      - /home/agent/.cache/huggingface
      # Allow writing to Python cache
      - /home/agent/.cache/pip:rw

volumes:
  agent_memory:
    driver: local
  model_cache:
    driver: local
