version: '3.8'

services:
  diagnostic-agent:
    build:
      context: .
      dockerfile: Dockerfile.fast.cross
    image: diagnostic-agent:fast-cross
    container_name: diagnostic-journalist
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./logs:/app/logs
      - ./models:/app/models
      - ./temp:/app/temp
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - FLASK_ENV=production
      - PYTHONPATH=/app
      - LOG_LEVEL=INFO
      - MODEL_CACHE_DIR=/app/models
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - diagnostic-net

networks:
  diagnostic-net:
    driver: bridge