# .github/workflows/deploy-to-pi.yml
name: Deploy to Raspberry Pi

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to Pi
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: picklegate.ddns.net
        port: 2222
        username: castlebravo
        key: ${{ secrets.PI_SSH_KEY }}
        script: |
          cd /home/castlebravo/diagnostic-agent
          git pull origin main
          docker-compose -f docker-compose.production.yml down
          docker build -f Dockerfile.fast.cross -t diagnostic-agent:latest .
          docker-compose -f docker-compose.production.yml up -d
          docker logs diagnostic-journalist --tail 10
